// Generated by scripts/rules/generate-registries.mjs. Do not edit by hand.
import type { Detector } from "../types.ts";
import { a11y001Detectors } from "./accessibility/A11Y-001-semantic-interactive-element.ts";
import { a11y002Detectors } from "./accessibility/A11Y-002-keyboard-interaction.ts";
import { a11y004Detectors } from "./accessibility/A11Y-004-accessible-control-name.ts";
import { core003Detectors } from "./core/CORE-003-prefer-const.ts";
import { gql002Detectors } from "./graphql/GQL-002-runtime-template-interpolation.ts";
import { i18n001Detectors } from "./internationalization/I18N-001-hardcoded-jsx-text.ts";
import { js001Detectors } from "./javascript/JS-001-redundant-async.ts";
import { js002Detectors } from "./javascript/JS-002-optional-chaining.ts";
import { js003Detectors } from "./javascript/JS-003-default-parameters.ts";
import { js004Detectors } from "./javascript/JS-004-namespace-safe-builtins.ts";
import { js006Detectors } from "./javascript/JS-006-non-mutating-collections.ts";
import { legend001Detectors } from "./legend-state/LEGEND-001-react-subscriptions.ts";
import { react004Detectors } from "./react/REACT-004-derived-state-effect.ts";
import { react006Detectors } from "./react/REACT-006-stable-list-keys.ts";
import { react008Detectors } from "./react/REACT-008-static-render-values.ts";
import { react009Detectors } from "./react/REACT-009-hook-placement.ts";
import { react010Detectors } from "./react/REACT-010-direct-component-calls.ts";
import { react011Detectors } from "./react/REACT-011-input-mutation.ts";
import { react012Detectors } from "./react/REACT-012-hook-dependency-suppressions.ts";
import { ts001Detectors } from "./typescript/TS-001-no-explicit-any.ts";
import { ts003Detectors } from "./typescript/TS-003-type-only-imports.ts";
import { ts004Detectors } from "./typescript/TS-004-untrusted-data-assertions.ts";
import { ts007Detectors } from "./typescript/TS-007-unsafe-unknown-assertions.ts";

export const detectors = [
  ...a11y001Detectors,
  ...a11y002Detectors,
  ...a11y004Detectors,
  ...core003Detectors,
  ...gql002Detectors,
  ...i18n001Detectors,
  ...js001Detectors,
  ...js002Detectors,
  ...js003Detectors,
  ...js004Detectors,
  ...js006Detectors,
  ...legend001Detectors,
  ...react004Detectors,
  ...react006Detectors,
  ...react008Detectors,
  ...react009Detectors,
  ...react010Detectors,
  ...react011Detectors,
  ...react012Detectors,
  ...ts001Detectors,
  ...ts003Detectors,
  ...ts004Detectors,
  ...ts007Detectors,
] satisfies readonly Detector[];
